"""pvm_candidates: PvM spawn candidates, gen_map_spawns parity, MapData files."""

import importlib.util
import os
from pathlib import Path

import pytest

from bsp_waypointer.analysis_graph import distance
from bsp_waypointer.constants import WaypointFlag
from bsp_waypointer.geometry_probe import BoxWorldProbe
from bsp_waypointer.pvm_candidates import (
    EXCLUDE,
    PvMParams,
    farthest_points,
    open_points,
    parse_pvm_nodes,
    pvm_candidates,
    resolve_pvm_nodes_path,
    teleport_blockers,
)
from bsp_waypointer.tactical_metrics import build_context

from .analysis_scenes import SceneBuilder, entities, hurt, open_world, spawn, teleporter

MAPDATA = """// Generated by tools/build/gen_map_spawns.py from x.rcw (ADR-0196).
"MapData"
{
\t"NpcSpawns"
\t{
\t\t"1 2 3" "x"
\t\t"4 5 6" "x"
\t\t"bad node" "x"
\t}
\t"LargeNpcSpawns" { "7 8 9" "x" }
\t"TeleportBlockers"
\t{
\t\t"10 11 12"\t"x"
\t\t"13 14 15 500"\t"x"
\t}
}
"""


def _field(nx=16, ny=16, step=64.0, flags=None):
    sb = SceneBuilder()
    ids = sb.add_grid(nx, ny, step=step)
    g = sb.graph()
    for i, f in (flags or {}).items():
        g.flags[i] = f
    return g, ids


def _run(g, ents, probe=None, **kw):
    ctx = build_context(g, ents, probe, seed=0, betweenness_samples=16)
    return ctx, pvm_candidates(ctx, PvMParams(**kw))


class TestPorts:
    POINTS = [(float(x), float(y), 0.0) for x in range(0, 1000, 70) for y in range(0, 700, 90)]

    def test_farthest_points_spacing_and_determinism(self):
        a = farthest_points(self.POINTS, 20, 160.0)
        assert a == farthest_points(self.POINTS, 20, 160.0)
        assert all(distance(p, q) >= 160.0 for i, p in enumerate(a) for q in a[i + 1:])

    def test_open_points_prefers_dense(self):
        pts = self.POINTS + [(2000.0, 2000.0, 0.0)]
        chosen = open_points(pts, 5, 192.0, 384.0)
        assert (2000.0, 2000.0, 0.0) not in chosen
        assert len(chosen) == 5

    def test_parity_with_gen_map_spawns(self):
        """When MC2's checkout is reachable, the ports match its functions exactly."""
        root = Path(os.environ.get("MC2_REPO", "C:/repos/mc2-ui-overhaul"))
        script = root / "tools" / "build" / "gen_map_spawns.py"
        if not script.exists():
            pytest.skip("MC2 checkout not found (set MC2_REPO)")
        spec = importlib.util.spec_from_file_location("gen_map_spawns", script)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        assert mod.EXCLUDE == EXCLUDE
        for k, s in ((10, 100.0), (40, 160.0), (200, 50.0)):
            assert farthest_points(self.POINTS, k, s) == mod.farthest_points(self.POINTS, k, s)
            assert open_points(self.POINTS, k, 192.0, s) == mod.open_points(self.POINTS, k, 192.0, s)


class TestMapData:
    def test_parse_sections_in_file_order(self):
        f = parse_pvm_nodes(MAPDATA)
        assert f.generated
        assert f.npc == [(1.0, 2.0, 3.0), (4.0, 5.0, 6.0)]
        assert f.large_npc == [(7.0, 8.0, 9.0)]
        assert f.teleport_blockers == [((10.0, 11.0, 12.0), None), ((13.0, 14.0, 15.0), 500.0)]

    def test_hand_authored_is_not_generated(self):
        assert not parse_pvm_nodes('"MapData" { "NpcSpawns" { "1 2 3" "x" } }').generated

    def test_resolve(self, tmp_path):
        (tmp_path / "dm_x.txt").write_text(MAPDATA, encoding="utf-8")
        assert resolve_pvm_nodes_path(tmp_path, "dm_x") == tmp_path / "dm_x.txt"
        assert resolve_pvm_nodes_path(tmp_path, "dm_y") is None
        assert resolve_pvm_nodes_path(tmp_path / "dm_x.txt", "anything") == tmp_path / "dm_x.txt"


class TestSelection:
    def test_exclusion_mask(self):
        jump = int(WaypointFlag.W_FL_JUMP)
        nored = int(WaypointFlag.W_FL_NORED)
        g, ids = _field(flags={ids_: jump for ids_ in range(16)} | {16: nored})
        ents = entities(
            spawns=[spawn(500, 500)],
            hurt=[hurt((-10, 600, -10), (300, 700, 10))],
            teleporters=[teleporter((0, 0, 0), (900, 900, 0))],
        )
        ctx, res = _run(g, ents, max_npc=500, spacing_small=1.0)
        chosen = {c["waypoint"] for c in res["npc"] + res["large_npc"]}
        assert chosen
        for w in chosen:
            o = g.origins[w]
            assert not g.flags[w] & (EXCLUDE | nored)
            assert distance(o, (500, 500, 0)) >= 192.0
            assert distance(o, (900, 900, 0)) >= 128.0
            assert not (-10 <= o[0] <= 300 and 600 <= o[1] <= 700)

    def test_spacing_and_determinism(self):
        g, _ = _field()
        ents = entities(spawns=[spawn(0, 0)])
        _, one = _run(g, ents)
        _, two = _run(g, ents)
        assert one == two
        npc = [c["origin"] for c in one["npc"]]
        assert len(npc) > 4
        assert all(distance(p, q) >= 160.0 for i, p in enumerate(npc) for q in npc[i + 1:])
        large = [c["origin"] for c in one["large_npc"]]
        assert all(distance(p, q) >= 384.0 for i, p in enumerate(large) for q in large[i + 1:])

    def test_candidates_are_lifted_and_scored(self):
        g, _ = _field()
        _, res = _run(g, entities(spawns=[spawn(0, 0)]))
        for c in res["npc"]:
            assert c["origin"][2] == pytest.approx(12.0)
            assert 0.0 <= c["score"] <= 1.0
            assert c["headroom"] is None and "no_ray_tracing" in c["reasons"]
            assert c["nearest_player_spawn"] >= 192.0
            assert c["in_hazard"] is False

    def test_far_from_spawn_scores_higher(self):
        g, _ = _field()
        _, res = _run(g, entities(spawns=[spawn(0, 0)]), max_npc=40)
        by_dist = sorted(res["npc"], key=lambda c: c["nearest_player_spawn"])
        assert by_dist[-1]["score"] > by_dist[0]["score"]

    def test_hull_and_headroom_refuse(self):
        g, _ = _field(nx=8, ny=8, step=64.0)
        # open everywhere, but a 60-unit ceiling over x < 200: no human fits there
        low = ((-100.0, -100.0, -16.0), (200.0, 1000.0, 60.0))
        high = ((200.0, -100.0, -16.0), (1000.0, 1000.0, 400.0))
        probe = BoxWorldProbe([low, high], step=4.0)
        _, res = _run(g, entities(spawns=[spawn(1000, 1000)]), probe, spacing_small=64.0)
        assert res["npc"]
        for c in res["npc"]:
            assert c["origin"][0] > 200.0 - 13.0
            assert c["headroom"] >= 72.0
        for c in res["large_npc"]:
            assert c["origin"][0] - 40.0 >= 200.0
            assert c["headroom"] >= 100.0

    def test_spawn_visibility_is_a_reason(self):
        g, _ = _field(nx=10, ny=10)
        _, res = _run(g, entities(spawns=[spawn(0, 0)]), open_world())
        assert any("spawn_visible" in c["reasons"] for c in res["npc"])

    def test_no_spawns(self):
        g, _ = _field(nx=6, ny=6)
        _, res = _run(g, entities())
        assert res["npc"] and all("no_player_spawns" in c["reasons"] for c in res["npc"])


class TestTeleportBlockers:
    def test_exits_and_unreachable_clusters(self):
        sb = SceneBuilder()
        sb.add_grid(4, 4)
        island = sb.add_grid(2, 2, x0=3000.0)
        g = sb.graph()
        ents = entities(spawns=[spawn(0, 0)], teleporters=[teleporter((0, 0, 0), (100, 50, 0))])
        ctx = build_context(g, ents, None)
        tb = teleport_blockers(ctx)
        reasons = [t["reason"] for t in tb]
        assert reasons == ["teleporter_exit", "unreachable_area"]
        assert tb[0]["origin"] == [100.0, 50.0, 0.0] and tb[0]["radius"] == 128.0
        assert tb[1]["origin"] == [3032.0, 32.0, 0.0]
        assert tb[1]["radius"] > 64.0
        assert island
