"""
PvM monster spawn candidates (spec §19), and MC2's spawn node files.

MC2's PvM director places monsters only at a map's spawn nodes,
``maps/graphs/<map>.txt`` (``"MapData" { "NpcSpawns" {...} "LargeNpcSpawns"
{...} "TeleportBlockers" {...} }``). MC2's ``tools/build/gen_map_spawns.py``
derives them from the waypoints by farthest-point sampling alone. This module
proposes them with reasons:

- the pool is the main component's waypoints that need no jump, crouch,
  ladder, lift or fall (``gen_map_spawns``'s exclusion mask), are not inside a
  lethal hurt volume or a one-team spawn guard, and keep clear of the player
  spawns (``SPAWN_EXCLUSION``) and teleporter exits (``TELEPORT_EXCLUSION``);
- ``npc`` nodes are picked by farthest-point sampling weighted by a pre-score
  (path distance from the player spawns, open ground), at least
  ``spacing_small`` apart, and each pick must fit the human hull
  (HULL_HUMAN, 26x26x72) ``lift`` units above the floor;
- ``large_npc`` nodes are the most open waypoints, ``spacing_large`` apart,
  that fit HULL_LARGE (80x80x100);
- every node is scored 0..1 on spawn distance, clearance, headroom, being out
  of the spawns' sight and away from teleporter exits, and carries reasons.

The game still surveys every node at level load and validates each spawn at
runtime (occupancy, visibility, entities); these candidates are advisory.
``farthest_points`` and ``open_points`` are verbatim ports of
``gen_map_spawns.py`` (a parity test pins them).
"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

from .analysis_graph import INF, SpatialIndex, connected_groups, distance
from .constants import WaypointFlag
from .tactical_metrics import AnalysisContext, nearest_straight, pt, rnd

Point = Tuple[float, float, float]

W_FL_JUMP = int(WaypointFlag.W_FL_JUMP)
W_FL_CROUCH = int(WaypointFlag.W_FL_CROUCH)
W_FL_UNREACHABLE = int(WaypointFlag.W_FL_UNREACHABLE)
W_FL_LADDER = int(WaypointFlag.W_FL_LADDER)
W_FL_LIFT = int(WaypointFlag.W_FL_LIFT)
W_FL_FALL = int(WaypointFlag.W_FL_FALL)
# gen_map_spawns.py's EXCLUDE, exactly
EXCLUDE = W_FL_JUMP | W_FL_CROUCH | W_FL_UNREACHABLE | W_FL_LADDER | W_FL_LIFT | W_FL_FALL
TEAM_BARRED = int(WaypointFlag.W_FL_NORED) | int(WaypointFlag.W_FL_NOBLU)

SPAWN_EXCLUSION = 192.0       # straight-line keep-out around a player spawn
TELEPORT_EXCLUSION = 128.0    # ... around a teleporter exit
HAZARD_NEAR = 64.0            # in_hazard: this close to a lethal hurt volume
SPAWN_NEAR_PATH = 384.0       # spawn-distance score is 0 at this path length ...
SPAWN_FAR_PATH = 1536.0       # ... and 1 at this one
SIGHT_RANGE = 1536.0          # spawns farther than this are not tested for sight
HEADROOM_PROBE = 256.0
TELEPORT_BLOCKER_RADIUS = 128.0
UNREACHABLE_AREA_MIN = 3      # an unreachable cluster this big gets a TeleportBlocker
TELEPORT_BLOCKERS_MAX = 64


# ---------------------------------------------------------------------------
# gen_map_spawns.py ports (keep verbatim: tests/test_pvm_candidates.py pins parity)
# ---------------------------------------------------------------------------


def dist2(a, b):
    return (a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2


def farthest_points(points, k, min_spacing):
    if not points:
        return []
    # Start from the point nearest the centroid, so the pick is deterministic.
    cx = sum(p[0] for p in points) / len(points)
    cy = sum(p[1] for p in points) / len(points)
    first = min(points, key=lambda p: (p[0] - cx) ** 2 + (p[1] - cy) ** 2)
    chosen = [first]
    best = [dist2(p, first) for p in points]
    min2 = min_spacing * min_spacing
    while len(chosen) < k:
        i = max(range(len(points)), key=lambda j: best[j])
        if best[i] < min2:
            break
        chosen.append(points[i])
        for j, p in enumerate(points):
            d = dist2(p, points[i])
            if d < best[j]:
                best[j] = d
    return chosen


def open_points(points, k, radius, spacing):
    r2 = radius * radius
    scored = []
    for p in points:
        n = sum(1 for q in points if dist2(p, q) <= r2)
        scored.append((n, p))
    scored.sort(key=lambda t: (-t[0], t[1]))
    chosen = []
    s2 = spacing * spacing
    for _, p in scored:
        if all(dist2(p, c) >= s2 for c in chosen):
            chosen.append(p)
            if len(chosen) >= k:
                break
    return chosen


# ---------------------------------------------------------------------------
# MC2 spawn node files (maps/graphs/<map>.txt)
# ---------------------------------------------------------------------------

_TOKEN_RE = re.compile(r'"([^"]*)"|([{}])|(//[^\n]*)|([^\s"{}]+)')
GENERATED_HEADER = "// Generated by tools/build/gen_map_spawns.py"


@dataclass
class PvMNodeFile:
    """The node sections of a ``maps/graphs/<map>.txt`` MapData file, in file order."""

    npc: List[Point] = field(default_factory=list)
    large_npc: List[Point] = field(default_factory=list)
    teleport_blockers: List[Tuple[Point, Optional[float]]] = field(default_factory=list)
    generated: bool = False   # starts with gen_map_spawns.py's header
    path: Optional[str] = None


def _node(text: str) -> Optional[Tuple[Point, Optional[float]]]:
    parts = text.split()
    if len(parts) not in (3, 4):
        return None
    try:
        vals = [float(p) for p in parts]
    except ValueError:
        return None
    if not all(math.isfinite(v) for v in vals):
        return None
    return (vals[0], vals[1], vals[2]), (vals[3] if len(vals) == 4 else None)


def parse_pvm_nodes(text: str) -> PvMNodeFile:
    """Parse MapData text. Unknown sections are skipped; a malformed node is skipped."""
    out = PvMNodeFile(generated=text.lstrip("﻿").startswith(GENERATED_HEADER))
    tokens: List[str] = []
    for m in _TOKEN_RE.finditer(text):
        if m.group(3):
            continue
        tokens.append(m.group(1) if m.group(1) is not None else (m.group(2) or m.group(4)))
    depth = 0
    section: Optional[str] = None
    i = 0
    while i < len(tokens):
        tok = tokens[i]
        if tok == "{":
            depth += 1
            i += 1
            continue
        if tok == "}":
            depth -= 1
            if depth <= 1:
                section = None
            i += 1
            continue
        nxt = tokens[i + 1] if i + 1 < len(tokens) else None
        if nxt == "{":
            if depth == 1:
                section = tok.lower()
            i += 1
            continue
        if nxt is None:
            break
        if depth == 2 and section is not None:
            node = _node(tok)
            if node is not None:
                if section == "npcspawns":
                    out.npc.append(node[0])
                elif section == "largenpcspawns":
                    out.large_npc.append(node[0])
                elif section == "teleportblockers":
                    out.teleport_blockers.append(node)
        i += 2
    return out


def load_pvm_nodes(path: Path) -> PvMNodeFile:
    data = Path(path).read_bytes()
    if data[:2] in (b"\xff\xfe", b"\xfe\xff"):
        raise ValueError(f"{path}: UTF-16 text (the game refuses it too)")
    nodes = parse_pvm_nodes(data.decode("utf-8", errors="replace"))
    nodes.path = Path(path).name
    return nodes


def resolve_pvm_nodes_path(option: Path, map_name: str) -> Optional[Path]:
    """``--pvm-nodes`` names a file, or a ``maps/graphs`` directory holding ``<map>.txt``."""
    option = Path(option)
    if option.is_dir():
        candidate = option / (map_name + ".txt")
        return candidate if candidate.exists() else None
    return option if option.exists() else None


# ---------------------------------------------------------------------------
# Candidates
# ---------------------------------------------------------------------------


@dataclass
class PvMParams:
    max_npc: int = 144
    max_large: int = 32
    spacing_small: float = 160.0
    spacing_large: float = 384.0
    open_radius: float = 192.0
    lift: float = 12.0
    hull_human: Tuple[float, float, float] = (26.0, 26.0, 72.0)
    hull_large: Tuple[float, float, float] = (80.0, 80.0, 100.0)


def hull_box(dims: Sequence[float]) -> Tuple[Point, Point]:
    w, d, h = float(dims[0]), float(dims[1]), float(dims[2])
    return (-w / 2.0, -d / 2.0, 0.0), (w / 2.0, d / 2.0, h)


def _clamp01(x: float) -> float:
    return 0.0 if x < 0.0 else 1.0 if x > 1.0 else x


@dataclass
class _Node:
    index: int
    origin: Point
    spawn_path: float          # path from the nearest player spawn (inf: none reaches)
    openness: float            # 0..1, neighbours within open_radius vs the pool's best
    tele: Optional[float]      # straight distance to the nearest teleporter exit
    pre: float = 0.0           # graph-only pre-score used by the selection


def candidate_pool(ctx: AnalysisContext, params: PvMParams) -> List[_Node]:
    """Eligible main waypoints with their graph-only measures, ascending by index."""
    g = ctx.graph
    spawn_pts = [s.origin for s in ctx.spawns]
    spawn_nodes = ctx.spawn_nodes()
    spawn_dist = ctx.dist_from(spawn_nodes) if spawn_nodes else [INF] * g.n
    eligible: List[int] = []
    for i in ctx.main_list:
        o = g.origins[i]
        if g.flags[i] & (EXCLUDE | TEAM_BARRED):
            continue
        if ctx.in_hazard(o):
            continue
        ns = nearest_straight(o, spawn_pts)
        if ns is not None and ns < SPAWN_EXCLUSION:
            continue
        nt = nearest_straight(o, ctx.teleport_exits)
        if nt is not None and nt < TELEPORT_EXCLUSION:
            continue
        eligible.append(i)
    index = SpatialIndex(g.origins, eligible, cell=params.open_radius)
    counts = {i: len(index.within(g.origins[i], params.open_radius)) for i in eligible}
    top = max(counts.values()) if counts else 1
    pool: List[_Node] = []
    for i in eligible:
        o = g.origins[i]
        node = _Node(i, o, spawn_dist[i], counts[i] / top if top else 0.0,
                     nearest_straight(o, ctx.teleport_exits))
        s_spawn = _spawn_score(node.spawn_path, bool(spawn_nodes))
        node.pre = 0.6 * s_spawn + 0.4 * node.openness
        pool.append(node)
    return pool


def _spawn_score(path: float, have_spawns: bool) -> float:
    if not have_spawns:
        return 1.0
    if path == INF:
        return 0.0
    return _clamp01((path - SPAWN_NEAR_PATH) / (SPAWN_FAR_PATH - SPAWN_NEAR_PATH))


def _tele_score(d: Optional[float]) -> float:
    if d is None:
        return 1.0
    return _clamp01((d - TELEPORT_EXCLUSION) / (512.0 - TELEPORT_EXCLUSION))


def _evaluate(ctx: AnalysisContext, node: _Node, hull: Tuple[Point, Point],
              min_headroom: float, lift: float) -> Optional[Dict[str, Any]]:
    """Trace-test and score one node. None when the hull does not fit."""
    probe = ctx.probe
    o = node.origin
    lifted = (o[0], o[1], o[2] + lift)
    have_spawns = bool(ctx.spawn_nodes())
    s_spawn = _spawn_score(node.spawn_path, have_spawns)
    s_tele = _tele_score(node.tele)
    near_hazard = ctx.in_hazard(o, HAZARD_NEAR)
    reasons: List[str] = []
    headroom: Optional[float] = None
    clearance: Optional[float] = None
    visible = False
    if probe is not None:
        if not probe.hull_fits(lifted, hull[0], hull[1]):
            return None
        headroom = probe.headroom(o, HEADROOM_PROBE)
        if headroom < min_headroom:
            return None
        rays = ctx.rays.get(node.index)
        if rays is None:
            rays = probe.clearances8(o, 512.0)
        clearance = sorted(rays)[len(rays) // 2]
        for s in ctx.spawns:
            if distance(s.origin, o) <= SIGHT_RANGE and probe.visible(s.origin, o):
                visible = True
                break
        s_clear = _clamp01(clearance / 256.0)
        s_head = _clamp01((headroom - min_headroom) / 64.0)
        score = (0.35 * s_spawn + 0.20 * s_clear + 0.15 * s_head
                 + 0.15 * (0.0 if visible else 1.0) + 0.15 * s_tele)
        if visible:
            reasons.append("spawn_visible")
        if clearance < 96.0:
            reasons.append("tight")
        if headroom < min_headroom + 32.0:
            reasons.append("low_headroom")
    else:
        score = 0.45 * s_spawn + 0.35 * node.openness + 0.20 * s_tele
        reasons.append("no_ray_tracing")
    if near_hazard:
        score *= 0.5
        reasons.append("near_hazard")
    if not have_spawns:
        reasons.append("no_player_spawns")
    elif node.spawn_path == INF:
        reasons.append("unreached_by_spawns")
    elif node.spawn_path < 768.0:
        reasons.append("near_player_spawn")
    if node.tele is not None and node.tele < 384.0:
        reasons.append("near_teleporter_exit")
    if ctx.degree(node.index) == 1:
        reasons.append("dead_end")
    if node.openness >= 0.75:
        reasons.append("open")
    return {
        "origin": pt(lifted),
        "score": rnd(score, 4),
        "headroom": rnd(headroom, 1),
        "clearance": rnd(clearance, 1),
        "nearest_player_spawn": rnd(node.spawn_path, 1),
        "nearest_teleporter": rnd(node.tele, 1),
        "in_hazard": near_hazard,
        "reasons": reasons,
        "waypoint": node.index,
    }


def _select_npc(ctx: AnalysisContext, pool: List[_Node], params: PvMParams) -> List[Dict[str, Any]]:
    """Score-weighted farthest-point sampling with per-pick hull validation."""
    if not pool:
        return []
    hull = hull_box(params.hull_human)
    min_head = float(params.hull_human[2])
    best = [INF] * len(pool)
    alive = [True] * len(pool)
    chosen: List[Dict[str, Any]] = []
    min2 = params.spacing_small * params.spacing_small
    first = True
    while len(chosen) < params.max_npc:
        pick = -1
        pick_val = -1.0
        for j, node in enumerate(pool):
            if not alive[j]:
                continue
            if first:
                val = node.pre
            else:
                if best[j] < min2:
                    continue
                val = math.sqrt(best[j]) * (0.5 + 0.5 * node.pre)
            if val > pick_val:
                pick, pick_val = j, val
        if pick < 0:
            break
        alive[pick] = False
        item = _evaluate(ctx, pool[pick], hull, min_head, params.lift)
        if item is None:
            continue  # refused: no distance update, the next best is tried
        first = False
        chosen.append(item)
        po = pool[pick].origin
        for j, node in enumerate(pool):
            d = dist2(node.origin, po)
            if d < best[j]:
                best[j] = d
    return chosen


def _select_large(ctx: AnalysisContext, pool: List[_Node], params: PvMParams) -> List[Dict[str, Any]]:
    """The most open waypoints, spacing_large apart, that fit the large hull."""
    hull = hull_box(params.hull_large)
    min_head = float(params.hull_large[2])
    order = sorted(pool, key=lambda n: (-n.openness, -n.pre, n.index))
    chosen: List[Dict[str, Any]] = []
    placed: List[Point] = []
    s2 = params.spacing_large * params.spacing_large
    for node in order:
        if len(chosen) >= params.max_large:
            break
        if any(dist2(node.origin, c) < s2 for c in placed):
            continue
        item = _evaluate(ctx, node, hull, min_head, params.lift)
        if item is None:
            continue
        chosen.append(item)
        placed.append(node.origin)
    return chosen


def teleport_blockers(ctx: AnalysisContext) -> List[Dict[str, Any]]:
    """TeleportBlocker suggestions: teleporter exits, and unreachable clusters.

    The Teleport module refuses a destination a blocker can see within its
    radius; a radius is always given (a bare triple means 1600 to the game).
    """
    out: List[Dict[str, Any]] = []
    for p in ctx.teleport_exits:
        out.append({"origin": pt(p), "radius": TELEPORT_BLOCKER_RADIUS, "reason": "teleporter_exit"})
    cls = ctx.comp.classification
    stuck = cls.sinks | cls.islands
    if stuck:
        g = ctx.graph
        und = g.undirected(stuck)
        groups = [grp for grp in connected_groups(und, stuck) if len(grp) >= UNREACHABLE_AREA_MIN]
        groups.sort(key=lambda grp: (-len(grp), grp[0]))
        for grp in groups:
            pts = [g.origins[i] for i in grp]
            c = (sum(p[0] for p in pts) / len(pts), sum(p[1] for p in pts) / len(pts),
                 sum(p[2] for p in pts) / len(pts))
            radius = max(distance(c, p) for p in pts) + 64.0
            out.append({"origin": pt(c), "radius": rnd(radius, 1), "reason": "unreachable_area"})
    return out[:TELEPORT_BLOCKERS_MAX]


def pvm_candidates(ctx: AnalysisContext, params: Optional[PvMParams] = None) -> Dict[str, Any]:
    """The ``candidates.pvm`` block of the analysis JSON."""
    params = params or PvMParams()
    pool = candidate_pool(ctx, params)
    npc = _select_npc(ctx, pool, params)
    large = _select_large(ctx, pool, params)
    return {
        "npc": npc,
        "large_npc": large,
        "teleport_blockers": teleport_blockers(ctx),
        "pool_size": len(pool),
    }
